# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fooditem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitems', to='registration.FoodItems'),
        ),
    ]
