# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20160306_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fooditem',
        ),
    ]
