# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_order_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
