# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_order_table_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='image',
            field=models.FileField(default=0, upload_to='/uploads'),
            preserve_default=False,
        ),
    ]
