# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20160310_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
